### ISSUE TITLE
V9 update needed for this line

### ISSUE THREAD

**Issue by datanerd3000** [webmaster94/Waterdeep-City-of-Splendors#1]
https://github.com/webmaster94/Waterdeep-City-of-Splendors/blob/acaf97f2963ab0fa467acdf9fe1af72d73cd1ca4/scripts/waterdeep.js#L26

With foundry v9, they've updated the underlying process.  I've found this works with v9 `canvas.scene.createEmbeddedDocuments("Note", noteDataResolved);` instead of `canvas.notes.createMany(noteDataResolved);`

**Comment by webmaster94** [comment]
Thank you for advising me on the syntax change in V9. I had not tried the script in v9 as I was still on v8 when I used it. I will evaluate the change you have suggested and let you know.

**Comment by webmaster94** [comment]
The module itself should work fine in v9 however. The script is only if you want to avoid using the content presented in the module.

**Comment by Gacky2k** [comment]
Works great!  Thank you for sharing!

**Comment by webmaster94** [comment]
@datanerd3000 sorry about the delay in the fix. I have been very busy and have not had time to check that the fix suggested works. I have now verified that and updated the script appropriately, thank you for your suggestion.
