### ISSUE TITLE
Entry text not appearing in journal

### ISSUE THREAD

**Issue by macagr** [webmaster94/Waterdeep-City-of-Splendors#3]
This may be a very noob question, but I'm just picking foundry up. I am importing the module successfully and it all seems to be working:

- Image is loading properly 
- Using the show notes module loads the items in the map 
- Entries in the journal are created

However, the entries in the journal are empty. I checked the JS file and I see it's just a variable `CityBuildings`, so I really don't understand why these entries are not showing up. Do you have an idea why? Otherwise I'll just keep playing around to see what may the issue be. Thanks!  

Further info: I'm using V12, although I don't see any breaking chnages in the release notes for that.

**Comment by webmaster94** [comment]
What version of Foundry are you using?

**Comment by macagr** [comment]
Version 12, I know it hasn't been ported, so I am wondering if the changes are breaking.

**Comment by macagr** [comment]
Managed to find the issue. It seems is the new pagination system they have. I will try to see if I can make it work on my side, and will make the PR so you can check if it makes sense to add it. For completeness, here's the link: [https://foundryvtt.com/api/interfaces/foundry.types.JournalEntryData.html](https://foundryvtt.com/api/interfaces/foundry.types.JournalEntryData.html ). I will close this issue.

**Comment by webmaster94** [comment]
I will update this when I get some time. I just haven't had the space to do it.
